---
# Variables used by the playbook. Override via `-e` or add to group_vars.
registry: ""               # e.g. myregistry.example.com/2300031147
tag: "latest"
namespace: music-platform
push_images: false          # if true, will docker push built images to `registry`
backend_image_name: "{{ (registry | trim != '') | ternary(registry + '/streaming-backend', 'streaming-backend') }}:{{ tag }}"
frontend_image_name: "{{ (registry | trim != '') | ternary(registry + '/streaming-frontend', 'streaming-frontend') }}:{{ tag }}"

# Database creds (use environment overrides or vault in production)
mysql_root_password: "1108"
mysql_database: "musicdb"
mysql_user: "root"
mysql_password: "1108"

# JWT secret (override in production)
jwt_secret: "CHANGE_ME_REPLACE_WITH_SECURE_VALUE"
